service: ${self:custom.appName}

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  httpApi:
    cors: true
  environment:
    TABLE_NAME: ${self:custom.tableName}
    STOCK_HISTORY_TABLE_NAME: ${self:custom.stockHistoryTableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt HouseholdItemsTable.Arn
            - !GetAtt StockHistoryTable.Arn

custom:
  appName: uchi-stock-app
  tableName: ${self:custom.appName}-items
  stockHistoryTableName: ${self:custom.appName}-stock-history

functions:
  createItem:
    handler: handler.createItem
    events:
      - http:
          path: items
          method: post
          cors: true
  getItems:
    handler: handler.getItems
    events:
      - http:
          path: items
          method: get
          cors: true
  updateItem:
    handler: handler.updateItem
    events:
      - http:
          path: items/{itemId}
          method: put
          cors: true
  deleteItem:
    handler: handler.deleteItem
    events:
      - http:
          path: items/{itemId}
          method: delete
          cors: true
  addStock:
    handler: handler.addStock
    events:
      - http:
          path: items/{itemId}/stock
          method: post
          cors: true
  consumeStock:
    handler: handler.consumeStock
    events:
      - http:
          path: items/{itemId}/consume
          method: post
          cors: true
  getConsumptionHistory:
    handler: handler.getConsumptionHistory
    events:
      - http:
          path: items/{itemId}/history
          method: get
          cors: true
  getEstimatedDepletionDate:
    handler: handler.getEstimatedDepletionDate
    events:
      - http:
          path: items/{itemId}/estimate
          method: get
          cors: true

resources:
  Resources:
    HouseholdItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    StockHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stockHistoryTableName}
        AttributeDefinitions:
          - AttributeName: historyId
            AttributeType: S
          - AttributeName: itemId
            AttributeType: S
        KeySchema:
          - AttributeName: historyId
            KeyType: HASH
          - AttributeName: itemId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
