service: karuta-app

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  environment:
    TABLE_NAME: ${self:custom.tableName}
    COMMENTS_TABLE_NAME: ${self:custom.commentsTableName}
    POLLY_CACHE_TABLE_NAME: ${self:custom.pollyCacheTableName} # 追加
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource: 
            - !GetAtt KarutaTable.Arn
            - !GetAtt CommentsTable.Arn
            - !GetAtt PollyCacheTable.Arn # 追加
        - Effect: Allow
          Action:
            - polly:SynthesizeSpeech
          Resource: "*"

custom:
  tableName: karuta-phrases
  commentsTableName: karuta-comments
  pollyCacheTableName: karuta-polly-cache # 追加

functions:
  getPhrase:
    handler: handler.getPhrase
    events:
      - http:
          path: get-phrase
          method: get
          cors: true
  getCategories:
    handler: handler.getCategories
    events:
      - http:
          path: get-categories
          method: get
          cors: true
  getCongratulationAudio:
    handler: handler.getCongratulationAudio
    events:
      - http:
          path: get-congratulation-audio
          method: get
          cors: true
  getPhrasesList:
    handler: handler.getPhrasesList
    events:
      - http:
          path: get-phrases-list
          method: get
          cors: true
  postComment:
    handler: handler.postComment
    events:
      - http:
          path: post-comment
          method: post
          cors: true
  getComments:
    handler: handler.getComments
    events:
      - http:
          path: get-comments
          method: get
          cors: true
  recordTime:
    handler: handler.recordTime
    events:
      - http:
          path: record-time
          method: post
          cors: true

resources:
  Resources:
    KarutaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: category
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: category
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    CommentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.commentsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    PollyCacheTable: # 追加
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.pollyCacheTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
